#version: "3"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: seguros-app
        container_name: seguros-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - seguros
        command: >
            sh -c "chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache &&
                    php-fpm"
    nginx:
        image: nginx:alpine
        container_name: seguros-nginx
        restart: unless-stopped
        ports:
            - "8001:80"
        volumes:
            - ./:/var/www
            - ./nginx/laravel.conf:/etc/nginx/conf.d/default.conf
        networks:
            - seguros

    db:
        image: mysql:8.0 # Use MySQL 8.0 which has ARM64 support
        container_name: seguros-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            # Remove MYSQL_USER and MYSQL_PASSWORD for root user
        ports:
            - "3308:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - seguros

networks:
    seguros:
        driver: bridge

volumes:
    dbdata:
        driver: local
